/**
 * Author:  Miguel Castro
 */
INSERT INTO `movie` (`title`, `gender`, `classification`, `description`) VALUES
('The Great Adventure', 'Action', 3, 'An epic journey across the world.'),
('Romantic Escapade', 'Romance', 4, 'A love story that transcends boundaries.'),
('Horror Nights', 'Horror', 5, 'A terrifying experience that will haunt you.'),
('Mystery of the Lost City', 'Mystery', 2, 'A quest to uncover ancient secrets.'),
('Laugh Out Loud', 'Comedy', 1, 'A hilarious comedy that will leave you in stitches.'),
('Sci-Fi Spectacular', 'Sci-Fi', 3, 'A futuristic tale of space and technology.'),
('The Detective Chronicles', 'Thriller', 4, 'A gripping thriller with unexpected twists.'),
('Animated Fun', 'Animation', 0, 'A delightful animated film for all ages.'),
('Documenting Reality', 'Documentary', 2, 'An insightful documentary on real events.'),
('Fantasy Realm', 'Fantasy', 3, 'A magical journey through a fantastical world.'),
('Underwater Odyssey', 'Adventure', 3, 'Explore the depths of the ocean in this thrilling adventure.'),
('Love in Paris', 'Romance', 4, 'A romantic tale set in the heart of Paris.'),
('Zombie Apocalypse', 'Horror', 5, 'Survive the undead in this chilling horror flick.'),
('The Art of Deception', 'Thriller', 4, 'A psychological thriller where nothing is as it seems.'),
('Space Explorers', 'Sci-Fi', 3, 'Join a crew on their mission to explore distant galaxies.'),
('Comedy Club Chaos', 'Comedy', 2, 'Hilarity ensues in this chaotic comedy club.'),
('Historical Journey', 'Drama', 3, 'Relive history in this epic drama.'),
('The Enigma Files', 'Mystery', 2, 'Solve mysteries with this brilliant detective.'),
('Fairy Tale Adventure', 'Fantasy', 2, 'A journey through a land of magic and wonder.'),
('Family Bonds', 'Family', 0, 'Discover the meaning of family in this heartwarming tale.'),
('Reality Bites', 'Drama', 4, 'Navigate the complexities of life in this gripping drama.'),
('Robots in Action', 'Sci-Fi', 2, 'Robots take center stage in this futuristic action film.'),
('The Haunted Mansion', 'Horror', 3, 'Explore the haunted secrets of an eerie mansion.'),
('Spy Games', 'Action', 3, 'Intrigue and espionage unfold in this action-packed thriller.'),
('The Lost World', 'Adventure', 3, 'Embark on a quest to uncover a lost civilization.'),
('Romantic Getaway', 'Romance', 3, 'Escape to romance in a picturesque setting.'),
('Superhero Origins', 'Action', 4, 'Witness the beginning of a legendary superhero.'),
('Laugh Riot', 'Comedy', 1, 'Prepare for non-stop laughter in this riotous comedy.'),
('Virtual Reality', 'Sci-Fi', 3, 'Step into a virtual world where anything is possible.'),
('Into the Unknown', 'Adventure', 2, 'Explore uncharted territories in this thrilling adventure.'),
('Criminal Minds', 'Thriller', 4, 'Enter the mind of a criminal mastermind in this intense thriller.'),
('Dark Fantasy', 'Fantasy', 4, 'A dark tale of magic and betrayal in a fantasy realm.'),
('Nature is Wonders', 'Documentary', 0, 'Witness the beauty and complexity of nature.'),
('Alien Encounter', 'Sci-Fi', 4, 'Encounter extraterrestrial beings in this sci-fi thriller.'),
('Heartfelt Drama', 'Drama', 3, 'Experience raw emotions in this heartfelt drama.'),
('Comedy of Errors', 'Comedy', 2, 'Mistaken identities lead to hilarious consequences.'),
('Paranormal Activity', 'Horror', 5, 'Experience the chilling effects of paranormal phenomena.'),
('Time Travelers', 'Sci-Fi', 3, 'Travel through time in this mind-bending sci-fi adventure.'),
('Murder Mystery', 'Mystery', 4, 'Solve a baffling murder mystery with unexpected twists.'),
('Dreamscape', 'Fantasy', 3, 'Explore a dreamscape where imagination knows no bounds.'),
('The Pursuit of Happiness', 'Drama', 4, 'Follow a journey of self-discovery and fulfillment.'),
('Oceanic Odyssey', 'Adventure', 3, 'Embark on an epic oceanic adventure.'),
('Cinematic Laughter', 'Comedy', 2, 'Laugh till you drop with this cinematic comedy.'),
('Intrigue and Deception', 'Thriller', 4, 'Navigate a web of intrigue and deception.'),
('Technological Wonders', 'Sci-Fi', 3, 'Witness the wonders of futuristic technology.'),
('Enchanted Forest', 'Fantasy', 2, 'Discover the secrets of an enchanted forest.'),
('Animal Kingdom', 'Documentary', 0, 'Explore the diverse habitats of Earth is animal kingdom.'),
('Ghostly Encounters', 'Horror', 3, 'Encounter ghosts and spirits in spine-chilling encounters.'),
('Epic Space Saga', 'Sci-Fi', 4, 'An epic saga set in the vastness of space.'),
('The Perfect Crime', 'Thriller', 4, 'Witness the execution of the perfect crime.'),
('Whimsical Wonderland', 'Fantasy', 3, 'Enter a whimsical wonderland of imagination.'),
('The Human Element', 'Documentary', 0, 'Explore the complexities of human behavior and society.'),
('Silent Screams', 'Horror', 5, 'Experience terror in silence with this intense horror film.'),
('The Ultimate Quest', 'Adventure', 3, 'Embark on the ultimate quest for truth and treasure.'),
('Spy Thriller', 'Thriller', 4, 'A gripping thriller filled with espionage and suspense.');
